server:
  port: 8062
  # 设置 session过期时间
  # PT 拼接 数值 拼接 H / M / S
  servlet:
    session:
      timeout: PT60M

spring:
  application:
    name: secret-sm
  profiles:
    active: dev
  main:
    allow-bean-definition-overriding: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 200MB


management:
  #port: 9000
  security:
    enabled: false
  endpoint:
    health:
      show-details: always

application:
  # 密评改造配置
  secret:
    app-id: APP_0FE9D4B351314168B29B6E810F81B33E
    url: http://192.159.104.123:13001/mssgApi/
    #  加解密字段 谨慎配置 匹配上就会 进行加解密 操作
    opt-field: phone,idCard,realName


#日志打印
logging:
  config: classpath:logback-spring-dev.xml

#debug: on
